[package]
name = "DNSserver"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "Dnspacket"
path = "src/DnsFunctions/Dnspacket.rs"

[[bin]]
name = "DnsResolver"
path = "src/DnsFunctions/DnsResolver.rs"
